title: Your awesome title
author: Jessica Higgins
email: jessicamichele97@gmail.com
description: > # this means to ignore newlines until "baseurl:"
I am a senior Computer Information Systems major. :)

# social links
twitter_username: your-twitter-handle
github_username:  Kroova

show_excerpts: false # set to false to remove excerpts on the homepage

theme: jekyll-theme-slate
