title: Technical Certificates
author: Jessica Higgins
email: jessicamichele97@gmail.com
description: > # this means to ignore newlines until "baseurl:"
i did these things and got these certs. 

# social links
github_username:  Kroova

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
